/**
 * generated by Xtext 2.18.0
 */
package net.ssehub.lea;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Analysis Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.ssehub.lea.AnalysisDefinition#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see net.ssehub.lea.LeaPackage#getAnalysisDefinition()
 * @model
 * @generated
 */
public interface AnalysisDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see net.ssehub.lea.LeaPackage#getAnalysisDefinition_Elements()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getElements();

} // AnalysisDefinition
