/**
 * generated by Xtext 2.18.0
 */
package net.ssehub.lea;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Analysis Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.ssehub.lea.AnalysisDefinition#getElementDeclarations <em>Element Declarations</em>}</li>
 *   <li>{@link net.ssehub.lea.AnalysisDefinition#getChangeIdentifierAssignments <em>Change Identifier Assignments</em>}</li>
 * </ul>
 *
 * @see net.ssehub.lea.LeaPackage#getAnalysisDefinition()
 * @model
 * @generated
 */
public interface AnalysisDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Element Declarations</b></em>' containment reference list.
   * The list contents are of type {@link net.ssehub.lea.ElementDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element Declarations</em>' containment reference list.
   * @see net.ssehub.lea.LeaPackage#getAnalysisDefinition_ElementDeclarations()
   * @model containment="true"
   * @generated
   */
  EList<ElementDeclaration> getElementDeclarations();

  /**
   * Returns the value of the '<em><b>Change Identifier Assignments</b></em>' containment reference list.
   * The list contents are of type {@link net.ssehub.lea.ChangeIdentifierAssignment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Change Identifier Assignments</em>' containment reference list.
   * @see net.ssehub.lea.LeaPackage#getAnalysisDefinition_ChangeIdentifierAssignments()
   * @model containment="true"
   * @generated
   */
  EList<ChangeIdentifierAssignment> getChangeIdentifierAssignments();

} // AnalysisDefinition
