/**
 * generated by Xtext 2.18.0
 */
package net.ssehub.lea;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Change Identifier Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.ssehub.lea.ChangeIdentifierAssignment#getIdentifier <em>Identifier</em>}</li>
 *   <li>{@link net.ssehub.lea.ChangeIdentifierAssignment#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see net.ssehub.lea.LeaPackage#getChangeIdentifierAssignment()
 * @model
 * @generated
 */
public interface ChangeIdentifierAssignment extends EObject
{
  /**
   * Returns the value of the '<em><b>Identifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifier</em>' attribute.
   * @see #setIdentifier(String)
   * @see net.ssehub.lea.LeaPackage#getChangeIdentifierAssignment_Identifier()
   * @model
   * @generated
   */
  String getIdentifier();

  /**
   * Sets the value of the '{@link net.ssehub.lea.ChangeIdentifierAssignment#getIdentifier <em>Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Identifier</em>' attribute.
   * @see #getIdentifier()
   * @generated
   */
  void setIdentifier(String value);

  /**
   * Returns the value of the '<em><b>Elements</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' attribute list.
   * @see net.ssehub.lea.LeaPackage#getChangeIdentifierAssignment_Elements()
   * @model unique="false"
   * @generated
   */
  EList<String> getElements();

} // ChangeIdentifierAssignment
