/**
 * generated by Xtext 2.18.0
 */
package net.ssehub.lea;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.ssehub.lea.ElementDeclaration#getGenericTyp <em>Generic Typ</em>}</li>
 *   <li>{@link net.ssehub.lea.ElementDeclaration#getParameterType <em>Parameter Type</em>}</li>
 *   <li>{@link net.ssehub.lea.ElementDeclaration#getSet <em>Set</em>}</li>
 *   <li>{@link net.ssehub.lea.ElementDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link net.ssehub.lea.ElementDeclaration#getInitialization <em>Initialization</em>}</li>
 * </ul>
 *
 * @see net.ssehub.lea.LeaPackage#getElementDeclaration()
 * @model
 * @generated
 */
public interface ElementDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Generic Typ</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Generic Typ</em>' attribute.
   * @see #setGenericTyp(String)
   * @see net.ssehub.lea.LeaPackage#getElementDeclaration_GenericTyp()
   * @model
   * @generated
   */
  String getGenericTyp();

  /**
   * Sets the value of the '{@link net.ssehub.lea.ElementDeclaration#getGenericTyp <em>Generic Typ</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Generic Typ</em>' attribute.
   * @see #getGenericTyp()
   * @generated
   */
  void setGenericTyp(String value);

  /**
   * Returns the value of the '<em><b>Parameter Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter Type</em>' attribute.
   * @see #setParameterType(String)
   * @see net.ssehub.lea.LeaPackage#getElementDeclaration_ParameterType()
   * @model
   * @generated
   */
  String getParameterType();

  /**
   * Sets the value of the '{@link net.ssehub.lea.ElementDeclaration#getParameterType <em>Parameter Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameter Type</em>' attribute.
   * @see #getParameterType()
   * @generated
   */
  void setParameterType(String value);

  /**
   * Returns the value of the '<em><b>Set</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Set</em>' containment reference.
   * @see #setSet(SetDefinition)
   * @see net.ssehub.lea.LeaPackage#getElementDeclaration_Set()
   * @model containment="true"
   * @generated
   */
  SetDefinition getSet();

  /**
   * Sets the value of the '{@link net.ssehub.lea.ElementDeclaration#getSet <em>Set</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Set</em>' containment reference.
   * @see #getSet()
   * @generated
   */
  void setSet(SetDefinition value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see net.ssehub.lea.LeaPackage#getElementDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link net.ssehub.lea.ElementDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Initialization</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initialization</em>' containment reference.
   * @see #setInitialization(Assignment)
   * @see net.ssehub.lea.LeaPackage#getElementDeclaration_Initialization()
   * @model containment="true"
   * @generated
   */
  Assignment getInitialization();

  /**
   * Sets the value of the '{@link net.ssehub.lea.ElementDeclaration#getInitialization <em>Initialization</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initialization</em>' containment reference.
   * @see #getInitialization()
   * @generated
   */
  void setInitialization(Assignment value);

} // ElementDeclaration
