/**
 * generated by Xtext 2.18.0
 */
package net.ssehub.lea;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Iteration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.ssehub.lea.Iteration#getIterator <em>Iterator</em>}</li>
 *   <li>{@link net.ssehub.lea.Iteration#getIterable <em>Iterable</em>}</li>
 * </ul>
 *
 * @see net.ssehub.lea.LeaPackage#getIteration()
 * @model
 * @generated
 */
public interface Iteration extends EObject
{
  /**
   * Returns the value of the '<em><b>Iterator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Iterator</em>' attribute.
   * @see #setIterator(String)
   * @see net.ssehub.lea.LeaPackage#getIteration_Iterator()
   * @model
   * @generated
   */
  String getIterator();

  /**
   * Sets the value of the '{@link net.ssehub.lea.Iteration#getIterator <em>Iterator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Iterator</em>' attribute.
   * @see #getIterator()
   * @generated
   */
  void setIterator(String value);

  /**
   * Returns the value of the '<em><b>Iterable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Iterable</em>' attribute.
   * @see #setIterable(String)
   * @see net.ssehub.lea.LeaPackage#getIteration_Iterable()
   * @model
   * @generated
   */
  String getIterable();

  /**
   * Sets the value of the '{@link net.ssehub.lea.Iteration#getIterable <em>Iterable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Iterable</em>' attribute.
   * @see #getIterable()
   * @generated
   */
  void setIterable(String value);

} // Iteration
