/**
 * generated by Xtext 2.18.0
 */
package net.ssehub.lea;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.ssehub.lea.Operation#getElement <em>Element</em>}</li>
 *   <li>{@link net.ssehub.lea.Operation#getCall <em>Call</em>}</li>
 * </ul>
 *
 * @see net.ssehub.lea.LeaPackage#getOperation()
 * @model
 * @generated
 */
public interface Operation extends EObject
{
  /**
   * Returns the value of the '<em><b>Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' attribute.
   * @see #setElement(String)
   * @see net.ssehub.lea.LeaPackage#getOperation_Element()
   * @model
   * @generated
   */
  String getElement();

  /**
   * Sets the value of the '{@link net.ssehub.lea.Operation#getElement <em>Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element</em>' attribute.
   * @see #getElement()
   * @generated
   */
  void setElement(String value);

  /**
   * Returns the value of the '<em><b>Call</b></em>' containment reference list.
   * The list contents are of type {@link net.ssehub.lea.Call}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Call</em>' containment reference list.
   * @see net.ssehub.lea.LeaPackage#getOperation_Call()
   * @model containment="true"
   * @generated
   */
  EList<Call> getCall();

} // Operation
