/**
 * generated by Xtext 2.18.0
 */
package net.ssehub.lea;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Result Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.ssehub.lea.ResultDeclaration#getType <em>Type</em>}</li>
 *   <li>{@link net.ssehub.lea.ResultDeclaration#getSet <em>Set</em>}</li>
 *   <li>{@link net.ssehub.lea.ResultDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link net.ssehub.lea.ResultDeclaration#getInitialization <em>Initialization</em>}</li>
 * </ul>
 *
 * @see net.ssehub.lea.LeaPackage#getResultDeclaration()
 * @model
 * @generated
 */
public interface ResultDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see net.ssehub.lea.LeaPackage#getResultDeclaration_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link net.ssehub.lea.ResultDeclaration#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Set</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Set</em>' containment reference.
   * @see #setSet(SetDefinition)
   * @see net.ssehub.lea.LeaPackage#getResultDeclaration_Set()
   * @model containment="true"
   * @generated
   */
  SetDefinition getSet();

  /**
   * Sets the value of the '{@link net.ssehub.lea.ResultDeclaration#getSet <em>Set</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Set</em>' containment reference.
   * @see #getSet()
   * @generated
   */
  void setSet(SetDefinition value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see net.ssehub.lea.LeaPackage#getResultDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link net.ssehub.lea.ResultDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Initialization</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initialization</em>' containment reference.
   * @see #setInitialization(Assignment)
   * @see net.ssehub.lea.LeaPackage#getResultDeclaration_Initialization()
   * @model containment="true"
   * @generated
   */
  Assignment getInitialization();

  /**
   * Sets the value of the '{@link net.ssehub.lea.ResultDeclaration#getInitialization <em>Initialization</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initialization</em>' containment reference.
   * @see #getInitialization()
   * @generated
   */
  void setInitialization(Assignment value);

} // ResultDeclaration
