/*
 * generated by Xtext 2.18.0
 */
package net.ssehub.parser.antlr;

import com.google.inject.Inject;
import net.ssehub.parser.antlr.internal.InternalLeaParser;
import net.ssehub.services.LeaGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LeaParser extends AbstractAntlrParser {

	@Inject
	private LeaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLeaParser createParser(XtextTokenStream stream) {
		return new InternalLeaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "AnalysisDefinition";
	}

	public LeaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LeaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
