/**
 * generated by Xtext 2.18.0
 */
package net.ssehub.lea.impl;

import net.ssehub.lea.Assignment;
import net.ssehub.lea.ElementDeclaration;
import net.ssehub.lea.LeaPackage;
import net.ssehub.lea.SetDefinition;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Element Declaration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link net.ssehub.lea.impl.ElementDeclarationImpl#getGenericTyp <em>Generic Typ</em>}</li>
 *   <li>{@link net.ssehub.lea.impl.ElementDeclarationImpl#getParameterType <em>Parameter Type</em>}</li>
 *   <li>{@link net.ssehub.lea.impl.ElementDeclarationImpl#getSet <em>Set</em>}</li>
 *   <li>{@link net.ssehub.lea.impl.ElementDeclarationImpl#getName <em>Name</em>}</li>
 *   <li>{@link net.ssehub.lea.impl.ElementDeclarationImpl#getInitialization <em>Initialization</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ElementDeclarationImpl extends MinimalEObjectImpl.Container implements ElementDeclaration
{
  /**
   * The default value of the '{@link #getGenericTyp() <em>Generic Typ</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGenericTyp()
   * @generated
   * @ordered
   */
  protected static final String GENERIC_TYP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getGenericTyp() <em>Generic Typ</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGenericTyp()
   * @generated
   * @ordered
   */
  protected String genericTyp = GENERIC_TYP_EDEFAULT;

  /**
   * The default value of the '{@link #getParameterType() <em>Parameter Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParameterType()
   * @generated
   * @ordered
   */
  protected static final String PARAMETER_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getParameterType() <em>Parameter Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParameterType()
   * @generated
   * @ordered
   */
  protected String parameterType = PARAMETER_TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getSet() <em>Set</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSet()
   * @generated
   * @ordered
   */
  protected SetDefinition set;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getInitialization() <em>Initialization</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitialization()
   * @generated
   * @ordered
   */
  protected Assignment initialization;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ElementDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LeaPackage.Literals.ELEMENT_DECLARATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getGenericTyp()
  {
    return genericTyp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGenericTyp(String newGenericTyp)
  {
    String oldGenericTyp = genericTyp;
    genericTyp = newGenericTyp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LeaPackage.ELEMENT_DECLARATION__GENERIC_TYP, oldGenericTyp, genericTyp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getParameterType()
  {
    return parameterType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setParameterType(String newParameterType)
  {
    String oldParameterType = parameterType;
    parameterType = newParameterType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LeaPackage.ELEMENT_DECLARATION__PARAMETER_TYPE, oldParameterType, parameterType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SetDefinition getSet()
  {
    return set;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSet(SetDefinition newSet, NotificationChain msgs)
  {
    SetDefinition oldSet = set;
    set = newSet;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LeaPackage.ELEMENT_DECLARATION__SET, oldSet, newSet);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSet(SetDefinition newSet)
  {
    if (newSet != set)
    {
      NotificationChain msgs = null;
      if (set != null)
        msgs = ((InternalEObject)set).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LeaPackage.ELEMENT_DECLARATION__SET, null, msgs);
      if (newSet != null)
        msgs = ((InternalEObject)newSet).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LeaPackage.ELEMENT_DECLARATION__SET, null, msgs);
      msgs = basicSetSet(newSet, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LeaPackage.ELEMENT_DECLARATION__SET, newSet, newSet));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LeaPackage.ELEMENT_DECLARATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Assignment getInitialization()
  {
    return initialization;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInitialization(Assignment newInitialization, NotificationChain msgs)
  {
    Assignment oldInitialization = initialization;
    initialization = newInitialization;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LeaPackage.ELEMENT_DECLARATION__INITIALIZATION, oldInitialization, newInitialization);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInitialization(Assignment newInitialization)
  {
    if (newInitialization != initialization)
    {
      NotificationChain msgs = null;
      if (initialization != null)
        msgs = ((InternalEObject)initialization).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LeaPackage.ELEMENT_DECLARATION__INITIALIZATION, null, msgs);
      if (newInitialization != null)
        msgs = ((InternalEObject)newInitialization).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LeaPackage.ELEMENT_DECLARATION__INITIALIZATION, null, msgs);
      msgs = basicSetInitialization(newInitialization, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LeaPackage.ELEMENT_DECLARATION__INITIALIZATION, newInitialization, newInitialization));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LeaPackage.ELEMENT_DECLARATION__SET:
        return basicSetSet(null, msgs);
      case LeaPackage.ELEMENT_DECLARATION__INITIALIZATION:
        return basicSetInitialization(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LeaPackage.ELEMENT_DECLARATION__GENERIC_TYP:
        return getGenericTyp();
      case LeaPackage.ELEMENT_DECLARATION__PARAMETER_TYPE:
        return getParameterType();
      case LeaPackage.ELEMENT_DECLARATION__SET:
        return getSet();
      case LeaPackage.ELEMENT_DECLARATION__NAME:
        return getName();
      case LeaPackage.ELEMENT_DECLARATION__INITIALIZATION:
        return getInitialization();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LeaPackage.ELEMENT_DECLARATION__GENERIC_TYP:
        setGenericTyp((String)newValue);
        return;
      case LeaPackage.ELEMENT_DECLARATION__PARAMETER_TYPE:
        setParameterType((String)newValue);
        return;
      case LeaPackage.ELEMENT_DECLARATION__SET:
        setSet((SetDefinition)newValue);
        return;
      case LeaPackage.ELEMENT_DECLARATION__NAME:
        setName((String)newValue);
        return;
      case LeaPackage.ELEMENT_DECLARATION__INITIALIZATION:
        setInitialization((Assignment)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LeaPackage.ELEMENT_DECLARATION__GENERIC_TYP:
        setGenericTyp(GENERIC_TYP_EDEFAULT);
        return;
      case LeaPackage.ELEMENT_DECLARATION__PARAMETER_TYPE:
        setParameterType(PARAMETER_TYPE_EDEFAULT);
        return;
      case LeaPackage.ELEMENT_DECLARATION__SET:
        setSet((SetDefinition)null);
        return;
      case LeaPackage.ELEMENT_DECLARATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case LeaPackage.ELEMENT_DECLARATION__INITIALIZATION:
        setInitialization((Assignment)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LeaPackage.ELEMENT_DECLARATION__GENERIC_TYP:
        return GENERIC_TYP_EDEFAULT == null ? genericTyp != null : !GENERIC_TYP_EDEFAULT.equals(genericTyp);
      case LeaPackage.ELEMENT_DECLARATION__PARAMETER_TYPE:
        return PARAMETER_TYPE_EDEFAULT == null ? parameterType != null : !PARAMETER_TYPE_EDEFAULT.equals(parameterType);
      case LeaPackage.ELEMENT_DECLARATION__SET:
        return set != null;
      case LeaPackage.ELEMENT_DECLARATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case LeaPackage.ELEMENT_DECLARATION__INITIALIZATION:
        return initialization != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (genericTyp: ");
    result.append(genericTyp);
    result.append(", parameterType: ");
    result.append(parameterType);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ElementDeclarationImpl
