/*
 * generated by Xtext 2.18.0
 */
package net.ssehub.ui;

import com.google.inject.Injector;
import net.ssehub.lea.ui.internal.LeaActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LeaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(LeaActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		LeaActivator activator = LeaActivator.getInstance();
		return activator != null ? activator.getInjector(LeaActivator.NET_SSEHUB_LEA) : null;
	}

}
