/*
 * generated by Xtext 2.18.0
 */
package net.ssehub.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

import net.ssehub.integration.LanguageElementException;
import net.ssehub.integration.LanguageRegistry;
import net.ssehub.ui.properties.LeaCoreConnector;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LeaUiModule extends AbstractLeaUiModule {

	public LeaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
		// TODO handle exeption in core connector?
		try {
            LeaCoreConnector.INSTANCE.provideLanguageElements();
        } catch (LanguageElementException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
	}
	
}
