/*
 * generated by Xtext 2.18.0
 */
package net.ssehub.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LeaUiModule extends AbstractLeaUiModule {

	public LeaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
