/*
 * generated by Xtext 2.18.0
 */
package net.ssehub.serializer;

import com.google.inject.Inject;
import java.util.List;
import net.ssehub.services.LeaGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class LeaSyntacticSequencer extends AbstractSyntacticSequencer {

	protected LeaGrammarAccess grammarAccess;
	protected AbstractElementAlias match_ArtifactDeclaration_SemicolonKeyword_7_q;
	protected AbstractElementAlias match_ChangeIdentifierAssignment_SemicolonKeyword_5_q;
	protected AbstractElementAlias match_FragmentDeclaration_SemicolonKeyword_7_q;
	protected AbstractElementAlias match_ResultDeclaration_SemicolonKeyword_7_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (LeaGrammarAccess) access;
		match_ArtifactDeclaration_SemicolonKeyword_7_q = new TokenAlias(false, true, grammarAccess.getArtifactDeclarationAccess().getSemicolonKeyword_7());
		match_ChangeIdentifierAssignment_SemicolonKeyword_5_q = new TokenAlias(false, true, grammarAccess.getChangeIdentifierAssignmentAccess().getSemicolonKeyword_5());
		match_FragmentDeclaration_SemicolonKeyword_7_q = new TokenAlias(false, true, grammarAccess.getFragmentDeclarationAccess().getSemicolonKeyword_7());
		match_ResultDeclaration_SemicolonKeyword_7_q = new TokenAlias(false, true, grammarAccess.getResultDeclarationAccess().getSemicolonKeyword_7());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_ArtifactDeclaration_SemicolonKeyword_7_q.equals(syntax))
				emit_ArtifactDeclaration_SemicolonKeyword_7_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ChangeIdentifierAssignment_SemicolonKeyword_5_q.equals(syntax))
				emit_ChangeIdentifierAssignment_SemicolonKeyword_5_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FragmentDeclaration_SemicolonKeyword_7_q.equals(syntax))
				emit_FragmentDeclaration_SemicolonKeyword_7_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ResultDeclaration_SemicolonKeyword_7_q.equals(syntax))
				emit_ResultDeclaration_SemicolonKeyword_7_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     initialization=Assignment (ambiguity) (rule end)
	 *     name=ID (ambiguity) (rule end)
	 */
	protected void emit_ArtifactDeclaration_SemicolonKeyword_7_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     elements+=ID (ambiguity) (rule end)
	 */
	protected void emit_ChangeIdentifierAssignment_SemicolonKeyword_5_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     initialization=Assignment (ambiguity) (rule end)
	 *     name=ID (ambiguity) (rule end)
	 */
	protected void emit_FragmentDeclaration_SemicolonKeyword_7_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     initialization=Assignment (ambiguity) (rule end)
	 *     name=ID (ambiguity) (rule end)
	 */
	protected void emit_ResultDeclaration_SemicolonKeyword_7_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
