/*
 * generated by Xtext 2.18.0
 */
package net.ssehub.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import net.ssehub.LeaRuntimeModule;
import net.ssehub.LeaStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LeaIdeSetup extends LeaStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LeaRuntimeModule(), new LeaIdeModule()));
	}
	
}
