/*
 * generated by Xtext 2.18.0
 */
package net.ssehub.ui.tests;

import com.google.inject.Injector;
import net.ssehub.lea.ui.internal.LeaActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class LeaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LeaActivator.getInstance().getInjector("net.ssehub.Lea");
	}

}
