/*
 * generated by Xtext 2.18.0
 */
package net.ssehub.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLeaScopeProvider extends DelegatingScopeProvider {
}
