/*
 * generated by Xtext 2.18.0
 */
package net.ssehub;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LeaStandaloneSetup extends LeaStandaloneSetupGenerated {

    /**
     * Creates the new setup.
     */
    public static void doSetup() {
        new LeaStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
}
