/*
 * generated by Xtext 2.18.0
 */
package net.ssehub;

import net.ssehub.integration.CoreLanguageElementCreator;
import net.ssehub.integration.LanguageElementException;
import net.ssehub.utilities.AbstractLogger;
import net.ssehub.utilities.LoggerFactory;
import net.ssehub.utilities.AbstractLogger.MessageType;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LeaStandaloneSetup extends LeaStandaloneSetupGenerated {
    
    /**
     * The identifier of this class, e.g. for printing messages.
     */
    private static final String ID = "LeaStandaloneSetup";
    
    /**
     * The current logger to use for printing information.
     */
    private static AbstractLogger logger = LoggerFactory.INSTANCE.getLogger();

    /**
     * Creates the new setup.
     */
    public static void doSetup() {
        new LeaStandaloneSetup().createInjectorAndDoEMFRegistration();
        
        CoreLanguageElementCreator coreLanguageElementCreator = new CoreLanguageElementCreator();
        try {
            logger.log(ID, "Creating core language elements", null, MessageType.DEBUG);
            coreLanguageElementCreator.createLanguageElements();
        } catch (LanguageElementException e) {
            logger.logException(ID, "Exception during core language element creation", e);
        }
    }
}
